#!/bin/bash

echo "Dodawanie użytkownika do grupy"

# zapytaj o grupe

echo "Proszę podaj nazwę grupy: "
read grupa

# Tworzenie grupy

addgroup $grupa

# Tworzenie użytkownika

echo "Podaj nazwę użytkownika: "
read login

# Dodawanie nowego użytkownika do grupy

useradd -m -G $grupa -s /bin/bash 
